### PR TITLE
Update to Angular 14

### PR DESCRIPTION
**Pull request by stefannikolei**
Updated the library to Angular V14

This enables the Ivy compilation. 

Otherwhise the library would not be able to be used in Angular V16 (ngcc was recently removed)

### CODE REVIEW

**Comment by scr2em** [comment]
MERGE THIS

**Comment by SimonKunz** [comment]
@matheusdavidson Is there any chance you'll merge this?

**Comment by RZR666** [comment]
Please merge +1

**Comment by matheusdavidson** [comment]
Hey Guys, I did the upgrade myself as I needed to change other things, will reject this PR but the package has been updated to v14.

From now on I'm following angular version so the package is also com v14.

**Pull request closed without merging**
